### ISSUE TITLE
LTR Building issue with newer GCC compilers

### ISSUE THREAD

**Issue by Zeitsperre** [johanvdw/SAGA-gis-git-mirror#9]
Been trying to get SAGA-GIS-LTR to work properly with QGIS on a Manjaro/Arch machine and was pulling my hair out. According to @nyalldawson, the issues arise from [SAGA not liking newer GCCs](https://gis.stackexchange.com/questions/285013/saga-gis-2-3-1-segmentation-fault-on-launch). I was wondering if this issue is being addressed in latest and/or LTR builds.

StackTrace:
   
       #####   ##   #####    ##
      ###     ###  ##       ###
       ###   # ## ##  #### # ##
        ### ##### ##    # #####
     ##### #   ##  ##### #   ##
    ____________________________

    SAGA Version: 2.3.1

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff6c491e6 in __strlen_sse2 () from /usr/lib/libc.so.6
    (gdb) bt
    #0  0x00007ffff6c491e6 in __strlen_sse2 () at /usr/lib/libc.so.6
    #1  0x00007ffff6c619c4 in __mbsrtowcs_l () at /usr/lib/libc.so.6
    #2  0x00007ffff7687b6f in wxMB2WC(wchar_t*, char const*, unsigned long) () 
    at /usr/lib/libwx_baseu-3.0.so.0
    #3  0x00007ffff7633b25 in wxMBConv::ToWChar(wchar_t*, unsigned long, char const*, unsigned long) const () at /usr/lib/libwx_baseu-3.0.so.0
    #4  0x00007ffff76344b0 in wxMBConv::cMB2WC(char const*, unsigned long,unsigned long*) const () at /usr/lib/libwx_baseu-3.0.so.0
    #5  0x00007ffff764402e in wxString::ConvertStr(char const*, unsigned long, wxMBConv const&) () at /usr/lib/libwx_baseu-3.0.so.0
    #6  0x0000555555560b0d in wxString::ImplStr(char const*, wxMBConv const&) ()
    #7  0x0000555555560c43 in wxString::wxString(char const*) ()
    #8  0x00007ffff7a493cb in CSG_String::CSG_String(char const*) ()
    at /usr/lib/libsaga_api-2.3.1.so
    #9  0x00007fffe64b3cf4 in CPROJ4_Base::_Init_Projection(CSG_Parameters&) ()
    at /usr/lib/saga/libpj_proj4.so
    #10 0x00007fffe64ae9a5 in CPROJ4_Base::CPROJ4_Base(int, bool) ()
    at /usr/lib/saga/libpj_proj4.so
    #11 0x00007fffe64be02a in CPROJ4_Shapes::CPROJ4_Shapes(int, bool) ()
    at /usr/lib/saga/libpj_proj4.so
    #12 0x00007fffe647ce3b in Create_Module(int) () at /usr/lib/saga/libpj_proj4.so
    #13 0x00007fffe647d27b in MLB_Initialize () at /usr/lib/saga/libpj_proj4.so
    #14 0x00007ffff7ad7cc6 in CSG_Module_Library::CSG_Module_Library(CSG_String const&) () at /usr/lib/libsaga_api-2.3.1.so
    #15 0x00007ffff7ad9e66 in CSG_Module_Library_Manager::Add_Library(wchar_t const*) () at /usr/lib/libsaga_api-2.3.1.so
    #16 0x00007ffff7ada341 in CSG_Module_Library_Manager::Add_Directory(wchar_t const*, bool) () at /usr/lib/libsaga_api-2.3.1.so
    #17 0x0000555555562e3a in  ()
    #18 0x0000555555562f17 in  ()
    #19 0x0000555555561e3c in  ()
    #20 0x0000555555561cd3 in  ()
    #21 0x00007ffff6bd506b in __libc_start_main () at /usr/lib/libc.so.6
    #22 0x000055555555b17a in  ()

**Comment by johanvdw** [comment]
Can you try compiling the 2.3 branch:
https://github.com/johanvdw/SAGA-gis-git-mirror/commits/release-2-3-lts

I should probably tag a release there.

**Comment by Zeitsperre** [comment]
Just finished compiling it and it seems to be working much better now (ie: it works). I'll try tagging the AUR guys to maybe point their source away from sourceforge and grab it directly fron this git branch (or tagged release). https://aur.archlinux.org/packages/saga-gis-ltr/

Thanks!

**Comment by johanvdw** [comment]
Don't change to this branch, I'll tag a release at sourceforge.

It will be 2.3.3. I will skip the 2.3.2 tag which is used on windows by
qgis to avoid confusion.

**Comment by Zeitsperre** [comment]
This hasn't been an issue for several years now. Thanks again for the help! Closing.
